backend:
    name: github
    repo: awesome1888/gannochenko
media_folder: static/assets
public_folder: assets
media_folder_relative: true
collections:
    - name: block
      label: Block
      folder: content/blocks
      create: true
      identifier_field: id
      fields:
          # https://www.netlifycms.org/docs/widgets/
          - name: id
            label: ID
          - name: sort
            label: Sort
            widget: number
            valueType: int
          - name: pathname
            label: Path name
            widget: string
          - name: body
            label: Body
            widget: markdown
          - label: Graphics
            name: graphics
            widget: list
            fields:
                - name: image
                  label: 'Image'
                  widget: 'image'
                  media_library:
                      config:
                      multiple: true
                - name: author
                  label: 'Author'
                  widget: string
                  required: false
                - name: source
                  label: 'Source'
                  widget: string
                  required: false
                - name: sourceText
                  label: 'Source text'
                  widget: string
                  required: false
